# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'E:/git/python/Calculator/calc.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(452, 775)
        MainWindow.setMinimumSize(QtCore.QSize(452, 775))
        MainWindow.setMaximumSize(QtCore.QSize(452, 775))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 139, 431, 783))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_5_7 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_5_7.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_5_7.setFont(font)
        self.pushButton_5_7.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_5_7.setObjectName("pushButton_5_7")
        self.gridLayout.addWidget(self.pushButton_5_7, 1, 3, 1, 1)
        self.pushButton_7_9 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_7_9.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_7_9.setFont(font)
        self.pushButton_7_9.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_7_9.setObjectName("pushButton_7_9")
        self.gridLayout.addWidget(self.pushButton_7_9, 1, 5, 1, 1)
        self.pushButton_15_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_15_3.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_15_3.setFont(font)
        self.pushButton_15_3.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_15_3.setObjectName("pushButton_15_3")
        self.gridLayout.addWidget(self.pushButton_15_3, 3, 5, 1, 1)
        self.pushButton_14_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_14_2.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_14_2.setFont(font)
        self.pushButton_14_2.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_14_2.setObjectName("pushButton_14_2")
        self.gridLayout.addWidget(self.pushButton_14_2, 3, 4, 1, 1)
        self.pushButton_6_8 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_6_8.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_6_8.setFont(font)
        self.pushButton_6_8.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_6_8.setObjectName("pushButton_6_8")
        self.gridLayout.addWidget(self.pushButton_6_8, 1, 4, 1, 1)
        self.pushButton_17_logs = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_17_logs.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_17_logs.setFont(font)
        self.pushButton_17_logs.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(169, 203, 213);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_17_logs.setObjectName("pushButton_17_logs")
        self.gridLayout.addWidget(self.pushButton_17_logs, 4, 3, 1, 1)
        self.pushButton_9_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_9_4.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_9_4.setFont(font)
        self.pushButton_9_4.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_9_4.setObjectName("pushButton_9_4")
        self.gridLayout.addWidget(self.pushButton_9_4, 2, 3, 1, 1)
        self.pushButton_3_sqrt = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_3_sqrt.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3_sqrt.setFont(font)
        self.pushButton_3_sqrt.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_3_sqrt.setObjectName("pushButton_3_sqrt")
        self.gridLayout.addWidget(self.pushButton_3_sqrt, 0, 5, 1, 1)
        self.pushButton_1_clear = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_1_clear.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_1_clear.setFont(font)
        self.pushButton_1_clear.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 95, 89);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_1_clear.setObjectName("pushButton_1_clear")
        self.gridLayout.addWidget(self.pushButton_1_clear, 0, 3, 1, 1)
        self.pushButton_19 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_19.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_19.setFont(font)
        self.pushButton_19.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(222, 232, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_19.setObjectName("pushButton_19")
        self.gridLayout.addWidget(self.pushButton_19, 4, 5, 1, 1)
        self.label = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 8, 3, 1, 4)
        self.pushButton_18_0 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_18_0.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_18_0.setFont(font)
        self.pushButton_18_0.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_18_0.setObjectName("pushButton_18_0")
        self.gridLayout.addWidget(self.pushButton_18_0, 4, 4, 1, 1)
        self.pushButton_4_x = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4_x.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4_x.setFont(font)
        self.pushButton_4_x.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_4_x.setObjectName("pushButton_4_x")
        self.gridLayout.addWidget(self.pushButton_4_x, 0, 6, 1, 1)
        self.pushButton_10_5 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_10_5.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_10_5.setFont(font)
        self.pushButton_10_5.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_10_5.setObjectName("pushButton_10_5")
        self.gridLayout.addWidget(self.pushButton_10_5, 2, 4, 1, 1)
        self.pushButton_16_sub = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_16_sub.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_16_sub.setFont(font)
        self.pushButton_16_sub.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(222, 232, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_16_sub.setObjectName("pushButton_16_sub")
        self.gridLayout.addWidget(self.pushButton_16_sub, 3, 6, 1, 1)
        self.pushButton_11_6 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_11_6.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_11_6.setFont(font)
        self.pushButton_11_6.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_11_6.setObjectName("pushButton_11_6")
        self.gridLayout.addWidget(self.pushButton_11_6, 2, 5, 1, 1)
        self.pushButton_13_1 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_13_1.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_13_1.setFont(font)
        self.pushButton_13_1.setStyleSheet(" QPushButton {\n"
"    background-color: rgb(238, 238, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_13_1.setObjectName("pushButton_13_1")
        self.gridLayout.addWidget(self.pushButton_13_1, 3, 3, 1, 1)
        self.pushButton_2_percent = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_2_percent.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_2_percent.setFont(font)
        self.pushButton_2_percent.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_2_percent.setObjectName("pushButton_2_percent")
        self.gridLayout.addWidget(self.pushButton_2_percent, 0, 4, 1, 1)
        self.pushButton_20_add = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_20_add.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_20_add.setFont(font)
        self.pushButton_20_add.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(222, 232, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_20_add.setObjectName("pushButton_20_add")
        self.gridLayout.addWidget(self.pushButton_20_add, 4, 6, 1, 1)
        self.pushButton_8_div = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_8_div.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_8_div.setFont(font)
        self.pushButton_8_div.setStyleSheet("QPushButton {\n"
"     background-color: rgb(222, 232, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_8_div.setObjectName("pushButton_8_div")
        self.gridLayout.addWidget(self.pushButton_8_div, 1, 6, 1, 1)
        self.pushButton_12_mult = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_12_mult.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_12_mult.setFont(font)
        self.pushButton_12_mult.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(222, 232, 255);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_12_mult.setObjectName("pushButton_12_mult")
        self.gridLayout.addWidget(self.pushButton_12_mult, 2, 6, 1, 1)
        self.pushButton_4_x_3 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4_x_3.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4_x_3.setFont(font)
        self.pushButton_4_x_3.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_4_x_3.setObjectName("pushButton_4_x_3")
        self.gridLayout.addWidget(self.pushButton_4_x_3, 5, 5, 1, 1)
        self.pushButton_21_eq = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_21_eq.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_21_eq.setFont(font)
        self.pushButton_21_eq.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(189, 255, 193);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_21_eq.setObjectName("pushButton_21_eq")
        self.gridLayout.addWidget(self.pushButton_21_eq, 5, 6, 1, 1)
        self.pushButton_4_x_2 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4_x_2.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4_x_2.setFont(font)
        self.pushButton_4_x_2.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_4_x_2.setObjectName("pushButton_4_x_2")
        self.gridLayout.addWidget(self.pushButton_4_x_2, 5, 4, 1, 1)
        self.pushButton_4_x_4 = QtWidgets.QPushButton(self.gridLayoutWidget)
        self.pushButton_4_x_4.setMinimumSize(QtCore.QSize(0, 90))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4_x_4.setFont(font)
        self.pushButton_4_x_4.setStyleSheet(" QPushButton {\n"
"     background-color: rgb(255, 253, 187);\n"
"     border-style: outset;\n"
"     border-width: 2px;\n"
"     border-radius: 10px;\n"
"     border-color: black;\n"
" }\n"
" QPushButton:pressed {\n"
"     background-color: rgb(111, 111, 111);\n"
"     border-style: inset;\n"
" }")
        self.pushButton_4_x_4.setObjectName("pushButton_4_x_4")
        self.gridLayout.addWidget(self.pushButton_4_x_4, 5, 3, 1, 1)
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(10, 10, 431, 121))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.textEdit.setFont(font)
        self.textEdit.setStyleSheet(" border-style: outset;\n"
" border-width: 2px;\n"
" border-radius: 10px;\n"
" border-color: black;")
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 452, 22))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menubar.setFont(font)
        self.menubar.setObjectName("menubar")
        self.menuMenu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.menuMenu.setFont(font)
        self.menuMenu.setObjectName("menuMenu")
        MainWindow.setMenuBar(self.menubar)
        self.actionAbout = QtWidgets.QAction(MainWindow)
        self.actionAbout.setObjectName("actionAbout")
        self.actionAbout_2 = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.actionAbout_2.setFont(font)
        self.actionAbout_2.setObjectName("actionAbout_2")
        self.menuMenu.addAction(self.actionAbout_2)
        self.menubar.addAction(self.menuMenu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Calculator"))
        self.pushButton_5_7.setText(_translate("MainWindow", "7"))
        self.pushButton_7_9.setText(_translate("MainWindow", "9"))
        self.pushButton_15_3.setText(_translate("MainWindow", "3"))
        self.pushButton_14_2.setText(_translate("MainWindow", "2"))
        self.pushButton_6_8.setText(_translate("MainWindow", "8"))
        self.pushButton_17_logs.setText(_translate("MainWindow", "Logs"))
        self.pushButton_9_4.setText(_translate("MainWindow", "4"))
        self.pushButton_3_sqrt.setText(_translate("MainWindow", "√"))
        self.pushButton_1_clear.setText(_translate("MainWindow", "C"))
        self.pushButton_19.setText(_translate("MainWindow", "."))
        self.pushButton_18_0.setText(_translate("MainWindow", "0"))
        self.pushButton_4_x.setText(_translate("MainWindow", "˂"))
        self.pushButton_10_5.setText(_translate("MainWindow", "5"))
        self.pushButton_16_sub.setText(_translate("MainWindow", "-"))
        self.pushButton_11_6.setText(_translate("MainWindow", "6"))
        self.pushButton_13_1.setText(_translate("MainWindow", "1"))
        self.pushButton_2_percent.setText(_translate("MainWindow", "%"))
        self.pushButton_20_add.setText(_translate("MainWindow", "+"))
        self.pushButton_8_div.setText(_translate("MainWindow", "/"))
        self.pushButton_12_mult.setText(_translate("MainWindow", "*"))
        self.pushButton_4_x_3.setText(_translate("MainWindow", ")"))
        self.pushButton_21_eq.setText(_translate("MainWindow", "="))
        self.pushButton_4_x_2.setText(_translate("MainWindow", "("))
        self.pushButton_4_x_4.setText(_translate("MainWindow", "j"))
        self.menuMenu.setTitle(_translate("MainWindow", "Menu"))
        self.actionAbout.setText(_translate("MainWindow", "Show log"))
        self.actionAbout_2.setText(_translate("MainWindow", "About"))
